var spracheaktiv="DE";
var sprachen=[
	{"language":"DE",
	 "description":"deutsch",
	 "words":{//"id":"wort in Sprache"
		 "loading":"lade daten...",
		 "meinTag":"mein Tag",
		 "meinProj":"meine Projekte",
		 "todo":"TODO",
		 "ueberblick":"Überblick",
		 "einstellungen":"Einstellungen",
		 "projekt":"Projekt",
		 "projekte":"Projekte",
		 "kunde":"Kunde",
		 "datum":"Datum",
		 "Tag":"Tag",
		 "Monat":"Monat",
		 "letzte12mon":"die letzten 12 Monate",
		 "filterby":"zeige Daten von ",
		 "zeigebeendete":"zeige beendete Projekte",
		 "datzeigebeendete":"zeige beendete Projekte",
		 "reststunden":"geplante Reststunden",
		 "circa":"ca.",
		 "ok":"OK",
		 "abbrechen":"abbrechen",
		 "addEintrag":"neuer Eintrag",
		 
		 "Januar":"Januar",
		 "Februar":"Februar",
		 "März":"März",
		 "April":"April",
		 "Mai":"Mai",
		 "Juni":"Juni",
		 "Juli":"Juli",
		 "August":"August",
		 "September":"September",
		 "Oktober":"Oktober",
		 "November":"November",
		 "Dezember":"Dezember",
		 "kurzJanuar":"Jan",
		 "kurzFebruar":"Feb",
		 "kurzMärz":"Mär",
		 "kurzApril":"Apr",
		 "kurzMai":"Mai",
		 "kurzJuni":"Jun",
		 "kurzJuli":"Jul",
		 "kurzAugust":"Aug",
		 "kurzSeptember":"Sep",
		 "kurzOktober":"Okt",
		 "kurzNovember":"Nov",
		 "kurzDezember":"Dez",
		 
		 "KalWoch":"KW",
		 
		 "Mo":"Mo",
		 "Di":"Di",
		 "Mi":"Mi",
		 "Do":"Do",
		 "Fr":"Fr",
		 "Sa":"Sa",
		 "So":"So",
		 "stdtaggesammt":"h/Tag",
		 "Kommentar":"Kommentar",
		 "worktyp":"Typ",
		 "Stunden":"Stunden",
		 "monatsauswertung":"Monatsauswertung",
		 "stundengesammt":"Arbeitsstunden im Monat: ",
		 "stundengesammt2":" von ",
		 "gesammtstunden":"Gesamtstunden",
		 "urlaub":"Urlaub",
		 "aenderungsaved":"Änderung gespeichert.",
		 "selectaday":"Wähle einen Tag!",
		 "firstcreateaprojekt":"Bitte erst ein Projekt anlegen.",
		 "selectaprojekt":"Welches Projekt soll eingefügt werden?",
		 "listegeladen":"Liste geladen.",
		 "deleteeintrag":"Eintrag löschen?",
		 "projtitel":"Projekttitel",
		 "Infos":"Infos",
		 "projid":"ProjektID / Dateiname",
		 "keinestunden":"Noch keine Stunden vorhanden.",
		 "projektexportierenCSV":"Projekt als CSV exportieren",
		 
		 "datisended":"Ist Projekt beendet?",
		 "datauftraggeber":"Auftraggeber",
		 "datprojektleiter":"Projektleiter",
		 "datstartdatum":"Startdatum",
		 "datenddatum":"Enddatum",
		 "datstatus":"Status",
		 "datprojektart":"Projektart",
		 "datgruppe":"Gruppe",
		 "dattage":"Tage",
		 "datland":"Land",
		 "datgeplantestunden":"geplante Stunden",
		 "datfarb":"Farbe",
		 
		 "dattodotext":"TODO-Listentext",
		 "datintodo":"in TODO-Liste?",
		 "dattodonr":"TODO-Listenposition",
		 "datfarbe":"Farbe",
		 
		 "datdat":"Datum",
		 "datstunden":"Stunden",
		 "dattyp":"Typ",
		 "datkommentar":"Kommentar",
		 "datuser":"Benutzer",
		 "datvonjahr":"von Jahr",
		  "datutagteiler":"Teiler",
		
		 "version":"Version",
		 "projektpage":"die Projektpage liegt auf",
		 "speicherort":"Deine Daten liegen in",
		 "progdownload":"Download der aktuellen Version",
		 
		 "wahleprojekt":"Wähle das zu bearbeitende Projekt aus!",
		 "buttdel":"löschen",
		 "inp_newProj":"Projektname",
		 "inp_filternamen":"suche",
		 "butt_newProj":"neues Projekt",
		 "butt_filternamen":"filtern",
		 "butt_viewpreMon":"zeige",
		 "butt_viewnexMon":"zeige",
		 "farbwaehler":"Farbe wählen",
		 "farbwaehlertitel":"Farbe wählen",
		 
		 "butt_entfernen":"von Liste entfernen",
		// "butt_up":"▲",
		// "butt_down":"▼",
		 "butt_move":"▲▼",
		 
		 "getnewProName":"Wie soll das neue Projekt heißen?",
		 "mesage_inputnamekurz":"Leider zu kurz, gebe bitte mindestens 3 Zeichen ein!",
		 "mesage_inputnamenoinput":"Ohne Name kann ich kein neues Projekt anlegen.",
		 
		 "datdefaulttyp":"Defaultstundentyp",
		 "datshowscramblebutt":"Developertoolbutton anzeigen",
		 "datstundenproArbeitstag":"Stunden pro Arbeitstag",
		 "datwochenarbeitstage":"Arbeitstage in der Woche",
		 "daturlabstageprojahr":"Urlaubstage pro Jahr",
		 "daturlabstageprojahrabjahr":"Urlaubstage pro Jahr gültig ab",
		 
		 "frei":"frei",
		 "waehletagimkalender":"Wählen einen Tag im Kalender!",
		 "tagsconbelegt":"Dieser Tag ist schon belegt, bitte wähle einen anderen.",
		 "tagistfeiertag":"Dieser Tag ein Feiertag, bitte wähle einen anderen.",
		 "tagistwochenende":"Urlaubstag am Wochenende setzen?",
		 "hinweisurlaubtab":"Hier siehst Du Deine Urlaubsverteilung, rechts die noch verfügbaren Tage. Wähle rechts einen freien Tag.<br>Bearbeite Deinen Eintrag bei 'meine Projekte'.",
		 "sonderurlaub":"Sonderurlaub",
		 
		 "zeige":"zeige",
		 "verberge":"verberge",
		 
		 "Autraggeber_zusammenfassen":"gleiche Auftraggeber zusammenfassen",
		 "Überstunden":"Überstunden",
		 "Reststunden":"Reststunden",
		 "Jahresüberstunden":"Jahresüberstunden",
		 "Jahresreststunden":"Jahresreststunden",
		 
		 "datsprache":"Sprache",
		 "hallo":"Hallo",
		 "togleConsole":"Console zeigen/verbergen",
		 "Stundeninfos":"Stundeninfos von",
		 "eintraginfos":"Infos zu diesem Eintrag",
		
		 "neueVersion":"Es gibt eine neue Version :-)"
		}
	},
	{"language":"EN",
	 "description":"english",
	 "words":{
		 "loading":"load data...",
		 "meinTag":"my day",
		 "meinProj":"my projects",
		 "todo":"TODO",
		 "ueberblick":"Overview",
		 "einstellungen":"Settings",
		 "projekt":"Project",
		 "projekte":"Projects",
		 "kunde":"Client",
		 "datum":"Date",
		 "Tag":"Day",
		 "Monat":"month",
		 "letzte12mon":"the last 12 months",
		 "filterby":"show data from ",
		 "zeigebeendete":"show finished projects",
		 "datzeigebeendete":"show finished projects",
		 "reststunden":"Planned remaining hours",
		 "circa":"approx.",
		 "ok":"OK",
		 "abbrechen":"cancel",
		 "addEintrag":"new entry",
		 
		 "Januar":"January",
		 "Februar":"Februrary",
		 "März":"March",
		 "April":"April",
		 "Mai":"May",
		 "Juni":"June",
		 "Juli":"July",
		 "August":"August",
		 "September":"September",
		 "Oktober":"October",
		 "November":"November",
		 "Dezember":"December",
		 "kurzJanuar":"Jan",
		 "kurzFebruar":"Feb",
		 "kurzMärz":"Mar",
		 "kurzApril":"Apr",
		 "kurzMai":"May",
		 "kurzJuni":"Jun",
		 "kurzJuli":"Jul",
		 "kurzAugust":"Aug",
		 "kurzSeptember":"Sep",
		 "kurzOktober":"Oct",
		 "kurzNovember":"Nov",
		 "kurzDezember":"Dec",
		 
		 "KalWoch":"CW",
		 
		 "Mo":"Mo",
		 "Di":"Tue",
		 "Mi":"Wed",
		 "Do":"Thu",
		 "Fr":"Fri",
		 "Sa":"Sat",
		 "So":"So",
		 "stdtaggesammt":"h/day",
		 "Kommentar":"Comment",
		 "worktyp":"Type",
		 "Stunden":"Hours",
		 "monatsauswertung":"Monthly report",
		 "stundengesammt":"Working hours per month: ",
		 "stundengesammt2":" from ",
		 "gesammtstunden":"Total hours",
		 "urlaub":"Vacation",
		 "aenderungsaved":"Change saved.",
		 "selectaday":"Choose a day!",
		 "firstcreateaprojekt":"Please create a project first.",
		 "selectaprojekt":"Which project should be inserted?",
		 "listegeladen":"List loaded.",
		 "deleteeintrag":"Delete entry?",
		 "projtitel":"Project title",
		 "Infos":"Info",
		 "projid":"ProjectID / file name",
		 "keinestunden":"No hours available yet.",
		 "projektexportierenCSV":"Export project as CSV",
		 
		 "datisended":"Is the project finished?",
		 "datauftraggeber":"Client",
		 "datprojektleiter":"Project manager",
		 "datstartdatum":"Start date",
		 "datenddatum":"End date",
		 "datstatus":"Status",
		 "datprojektart":"Project type",
		 "datgruppe":"Group",
		 "dattage":"days",
		 "datland":"Country",
		 "datgeplantestunden":"planned hours",
		 "datfarb":"Color",
		 
		 "dattodotext":"TODO list text",
		 "datintodo":"in TODO list?",
		 "dattodonr":"TODO list item",
		 "datfarbe":"Color",
		 
		 "datdat":"Date",
		 "datstunden":"Hours",
		 "dattyp":"Type",
		 "datkommentar":"Comment",
		 "datuser":"Users",
		 "datvonjahr":"from year",
		  "datutagteiler":"Divider",
		
		 "version":"Version",
		 "projektpage":"the project page is on",
		 "speicherort":"Your data is stored in",
		 "progdownload":"Download the current version",
		 
		 "wahleprojekt":"Select the project to be edited!",
		 "buttdel":"delete",
		 "inp_newProj":"Project name",
		 "inp_filternamen":"search",
		 "butt_newProj":"new project",
		 "butt_filternamen":"filter",
		 "butt_viewpreMon":"show",
		 "butt_viewnexMon":"show",
		 "farbwaehler":"Choose color",
		 "farbwaehlertitel":"Choose color",
		 
		 "butt_entfernen":"Remove from list",
		// "butt_up":"▲",
		// "butt_down":"▼",
		 "butt_move":"▲▼",
		 
		 "getnewProName":"What should the new project be called?",
		 "mesage_inputnamekurz":"Unfortunately too short, please enter at least 3 characters!",
		 "mesage_inputnamenoinput":"I cannot create a new project without a name.",
		 
		 "datdefaulttyp":"Default hour type",
		 "datshowscramblebutt":"Show developer tool button",
		 "datstundenproArbeitstag":"Hours per working day",
		 "datwochenarbeitstage":"Working days per week",
		 "daturlabstageprojahr":"Vacation days per year",
		 "daturlabstageprojahrabjahr":"Vacation days per year valid from",
		 
		 "frei":"free",
		 "waehletagimkalender":"Choose a day in the calendar!",
		 "tagsconbelegt":"This day is already occupied, please choose another one.",
		 "tagistfeiertag":"This day is a public holiday, please choose another one.",
		 "tagistwochenende":"Set a vacation day on the weekend?",
		 "hinweisurlaubtab":"Here you can see your vacation distribution, on the right the days still available. Select a day off on the right.<br>Edit your entry under 'my projects'.",
		 "sonderurlaub":"Special vacation",
		 
		 "zeige":"show",
		 "verberge":"hide",
		 
		 "Autraggeber_zusammenfassen":"summarize the same clients",
		 "Überstunden":"Overtime",
		 "Reststunden":"Remaining hours",
		 "Jahresüberstunden":"Annual overtime",
		 "Jahresreststunden":"Remaining annual hours",
		 
		 "datsprache":"Language",
		 "hallo":"hello",
		 "togleConsole":"togle Console",		 
		 "Stundeninfos":"Hourly information from",
		 "eintraginfos":"Info about this entry",
		
		 "neueVersion":"A new version is available :-)"	 }
	}
];


var getWort=function(s){
	var i,spra;
	for(i=0;i<sprachen.length;i++){
		spra=sprachen[i];
		if(spra.language==spracheaktiv){
			if(spra.words[s]!=undefined)
				return spra.words[s];		//gefunden Übersetzung zurückgeben
		}
	}	
	return s; //nicht gefunden, Eingabe zurückgeben
};

